### ISSUE TITLE
The same markdown file name in different directories will cause incorrect links

### ISSUE THREAD

**Issue by carvinlo** [svsool/vscode-memo#126] opened 2020-09-23 01:21 UTC
The same markdown file name in different directories will cause incorrect links. For example, the following scenario:

First step, linking `questions/02-started.md` document in `tutorials/01-intro.md` document
`tutorials/01-intro.md`
```markdown
This is some text, link [[02-started]]
```
`questions/02-started.md`
```markdown
Do something.
```
Second step, add a `tutorials/02-started.md` document in the `tutorials` folder. 
This will cause the `[[02-started]]` link in the `tutorials/01-intro.md` document points to the `tutorials/02-started.md` document in the newly created `tutorials` directory.

Can supporting relative paths solve this scenario?

**Comment by svsool** [comment] 2020-09-24 15:15
> This will cause the [[02-started]] link in the tutorials/01-intro.md document points to the tutorials/02-started.md document in the newly created tutorials directory.

Unable to reproduce. I went through the steps and found that Memo will open expected file `questions/02-started.md` instead of `tutorials/02-started.md`.

![issue #120](https://user-images.githubusercontent.com/1452141/94162637-99a92900-fe8f-11ea-8189-38eda96d79f7.gif)

> Can supporting relative paths solve this scenario?

Memo already supports relative links and uses them in case of filename duplicates. You can create multiple files with the same name in different files and start linking those in some file, you will see how Memo adds relative links on autocomplete. Given duplicate filenames, short link will always be pointing to the file that comes first in the workspace tree or in the autocomplete results after applying natural sorting. Knowing this, I think you can change the repro steps or order of the files to reproduce the problem you mentioned, but in general, this is how Memo works. When I was using Obsidian.md, which also uses short links where possible and long links in all other cases, that understanding came almost intuitively. About always using relative links that would work with files first approach, but not with links first approach. Some users create files first, where others create links first.

```
/a.md - can be referenced via short ref as [[a]], since it comes first after paths sorting
/folder1/a.md - can be referenced only via long ref as [[folder1/a]]
/folder2/subfolder1/a.md - can be referenced only via long ref as [[folder2/subfolder1/a]]
```

**Comment by carvinlo** [comment] 2020-09-25 02:20
Thank you for your patience and precious time. Sorry for my mistake, I missed the last critical step: 
Third step, when any content of `tutorials/01-intro.md` is re-edited and saved, the `[[02-started]]` link point was changed.

**Comment by carvinlo** [comment] 2020-09-30 23:52
I use some other software (Obsidian) that supports bidirectional connection to deal with this scenario (when creating the same document in different directories), it will automatically update `shortest path when possible` to `absolute path in vault`.
![image](https://user-images.githubusercontent.com/5674761/94750879-b4acf900-03b9-11eb-8287-bc6be1252ecf.png)

![image](https://user-images.githubusercontent.com/5674761/94750658-246eb400-03b9-11eb-9f6c-9e24482bccc9.png)

**Comment by svsool** [comment] 2020-10-03 11:29
Hello, thanks for checking that and sharing here. There is one part of it https://github.com/svsool/vscode-memo/pull/131 was already merged today. Thanks @jojanaho for contributing. I still have to look into links syncing for that case.

**Comment by svsool** [comment] 2020-10-31 20:24
[v3.0](https://github.com/svsool/vscode-memo/releases/tag/v0.3.0) was released today and now links format can be changed in the settings:

![tg_image_2305958149](https://user-images.githubusercontent.com/1452141/97789263-bee43200-1bc7-11eb-845c-bcaaaca38122.jpeg)

**Closed by svsool** 2020-10-31 20:24 UTC
