### ISSUE TITLE
[request] Configure newNoteDirectory && slugifyCharacter

### ISSUE THREAD

**Issue by faydanube** [svsool/vscode-memo#287] opened 2021-02-28 12:09 UTC
It would be nice if memo could do the same thing. Configure the directory, filename, and default title of the files created by [[wiki_link]]

I am now using both `Markdown Notes` and `vscode-memo` and have made the following configuration

```json
"vscodeMarkdownNotes.newNoteDirectory": "SAME_AS_ACTIVE_NOTE",
"vscodeMarkdownNotes.slugifyCharacter": "_", // `[[wiki-links]]` -> `[[wiki_links]]`
"memo.links.following.enabled": false, // 
```

**Comment by svsool** [comment] 2021-03-11 18:29
Hi, slugification won't be done because of reasons described in this issue https://github.com/svsool/vscode-memo/issues/16.

About new note directory it's a duplicate of https://github.com/svsool/vscode-memo/issues/38.

**Closed by svsool** 2021-03-11 18:29 UTC
